`timescale 1ns / 1ps

module riscv_top (
    input wire clk,
    input wire reset,

    // Debug Ports
    output wire [31:0] debug_pc,
    output wire [31:0] debug_instruction,
    output wire [31:0] debug_if_id_pc,
    output wire [31:0] debug_if_id_instruction,
    output wire [31:0] debug_read_data1,
    output wire [31:0] debug_read_data2,
    output wire [31:0] debug_imm,
    output wire [4:0]  debug_id_rs1,
    output wire [4:0]  debug_id_rs2,
    output wire [4:0]  debug_id_rd,
    output wire [31:0] debug_id_ex_pc,
    output wire [4:0]  debug_id_ex_rs1,
    output wire [4:0]  debug_id_ex_rs2,
    output wire [4:0]  debug_id_ex_rd,
    output wire [31:0] debug_alu_result,
    output wire [2:0]  debug_ALUControl,
    output wire        debug_Zero,
    output wire [1:0]  debug_ForwardA,
    output wire [1:0]  debug_ForwardB,
    output wire        debug_stall,
    output wire        debug_flush,
    output wire [31:0] debug_ex_mem_alu_result,
    output wire [4:0]  debug_ex_mem_rd,
    output wire        debug_ex_mem_RegWrite,
    output wire        debug_ex_mem_MemWrite,
    output wire [31:0] debug_read_data,
    output wire [31:0] debug_mem_wb_alu_result,
    output wire [31:0] debug_mem_wb_mem_data,
    output wire [4:0]  debug_mem_wb_rd,
    output wire [31:0] debug_writeback,
    output wire        debug_mem_wb_RegWrite,
    output wire        debug_RegWrite,
    output wire        debug_MemWrite,
    output wire        debug_Branch,
    output wire        debug_Jump,
    output wire        debug_ALUSrc,
    output wire        debug_MemtoReg
);

    // Core Instantiation
    Datapath_Pipelined core (
        .clk(clk),
        .reset(reset),
        .debug_pc(debug_pc),
        .debug_instruction(debug_instruction),
        .debug_if_id_pc(debug_if_id_pc),
        .debug_if_id_instruction(debug_if_id_instruction),
        .debug_read_data1(debug_read_data1),
        .debug_read_data2(debug_read_data2),
        .debug_imm(debug_imm),
        .debug_id_rs1(debug_id_rs1),
        .debug_id_rs2(debug_id_rs2),
        .debug_id_rd(debug_id_rd),
        .debug_id_ex_pc(debug_id_ex_pc),
        .debug_id_ex_rs1(debug_id_ex_rs1),
        .debug_id_ex_rs2(debug_id_ex_rs2),
        .debug_id_ex_rd(debug_id_ex_rd),
        .debug_alu_result(debug_alu_result),
        .debug_ALUControl(debug_ALUControl),
        .debug_Zero(debug_Zero),
        .debug_ForwardA(debug_ForwardA),
        .debug_ForwardB(debug_ForwardB),
        .debug_stall(debug_stall),
        .debug_flush(debug_flush),
        .debug_ex_mem_alu_result(debug_ex_mem_alu_result),
        .debug_ex_mem_rd(debug_ex_mem_rd),
        .debug_ex_mem_RegWrite(debug_ex_mem_RegWrite),
        .debug_ex_mem_MemWrite(debug_ex_mem_MemWrite),
        .debug_read_data(debug_read_data),
        .debug_mem_wb_alu_result(debug_mem_wb_alu_result),
        .debug_mem_wb_mem_data(debug_mem_wb_mem_data),
        .debug_mem_wb_rd(debug_mem_wb_rd),
        .debug_writeback(debug_writeback),
        .debug_mem_wb_RegWrite(debug_mem_wb_RegWrite),
        .debug_RegWrite(debug_RegWrite),
        .debug_MemWrite(debug_MemWrite),
        .debug_Branch(debug_Branch),
        .debug_Jump(debug_Jump),
        .debug_ALUSrc(debug_ALUSrc),
        .debug_MemtoReg(debug_MemtoReg)
    );

endmodule
